### ISSUE TITLE
Замечания по 2 лабе

### ISSUE THREAD

**Issue by Andreanapolicy** [mosssy1/OOP#2]
# Вектор
1. `using namespace std` лучше не использовать, так как в дальнейшем может произойти конфликт имен переменных
2. `MuitiplyByMin` лучше заменить на `MultiplyByMin`. В оригинальном названии очепятка
3. [Вот тут можно убрать условие и возвращать `v.size() > 0`](https://github.com/mosssy1/OOP/blob/2716536192f88cc2e9d60412edcd1b202e9713fb/lab2/Vector/Vector/CVectorProcessor.cpp#L31)
4. [Вот тут](https://github.com/mosssy1/OOP/blob/2716536192f88cc2e9d60412edcd1b202e9713fb/lab2/Vector/Vector/Vector.cpp#L21) лучше не вызывать `sort` на прямую. Будет идеальным вариантом вынести отдельный метод у модуля `CVectorProcessor` и вызывать его опционально(не вызывать в MultiplyByMin)
5. В тесты необходимо добавить проверку, какой вектор создался после функции `ParseFloatsToVector`. Сейчас проверяется только то, что функция вернула true
6. [Вот тут](https://github.com/mosssy1/OOP/blob/2716536192f88cc2e9d60412edcd1b202e9713fb/lab2/Vector/Vector/CVectorProcessor.cpp#L41) лучше воспользоваться методом `transform`

**Итог**
Пока ставлю `20*0.6*0.4 = 4.8` и доп `10*0.6*1 = 6`

# HtmlDecode
1. Тестов не хватает. Предлагаю проверить:
- html-сущность в начале
- в конце
2. [Вот тут](https://github.com/mosssy1/OOP/blob/2716536192f88cc2e9d60412edcd1b202e9713fb/lab2/HtmlDecode/HtmlDecode/HtmlDecode.cpp#L17) лучше не называть функции одинаково, так как легко перепутать.
3. [Зачем здесь стоит `try...catch`](https://github.com/mosssy1/OOP/blob/2716536192f88cc2e9d60412edcd1b202e9713fb/lab2/HtmlDecode/HtmlDecode/HtmlDecode.cpp#L21)?
4. [Вот тут ](https://github.com/mosssy1/OOP/blob/2716536192f88cc2e9d60412edcd1b202e9713fb/lab2/HtmlDecode/HtmlDecode/HtmlDecodeProcessor.cpp#L1) можно не указывать подключение `string`, так как он уже подключается в заголовочном файле. 
5. [Вот тут ](https://github.com/mosssy1/OOP/blob/2716536192f88cc2e9d60412edcd1b202e9713fb/lab2/HtmlDecode/HtmlDecode/HtmlDecodeProcessor.cpp#L1) нужно подключать заголовочный файл. https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BE%D1%87%D0%BD%D1%8B%D0%B9_%D1%84%D0%B0%D0%B9%D0%BB
6. [Функция](https://github.com/mosssy1/OOP/blob/2716536192f88cc2e9d60412edcd1b202e9713fb/lab2/HtmlDecode/HtmlDecode/HtmlDecodeProcessor.cpp#L14) оказалась большой и она имеет повторяющиеся фрагменты. Убери повторы и разбей функцию на логические шаги и выдели их в функции

**Итог**
Пока ставлю `60*0.6*0.4 = 14.4`

# Dictionary
1. Не работает регистр независимость с русскими словами
2. Тестов явно не хватает. Стоит проверить: добавление одинаковых слов, одинаковых переводов, пустых переводов. 
3. Стоит подумать над разделением ответственности: в модуль `DictionaryProcessor ` не стоит выносить работу с консолью(метод `LoadWordWithTranslationToDictionary` лучше преобразовать в метод `TryToAddTranslationDictionary(Dictionary, word, translation)`). Так будет и проще покрыть этот код тестами, и разделить `UI - CORE`
4. `StringToLower` - функция, которая не имеет отношений к работе Dictionary. Лучше вынести в отдельный модуль `StringUtils`
5. МБ стоит не создавать метод `GetDIctionary`, а использовать `LoadDIctionary`?
6. Вынести в модуль Dictionary метод `GetTranslations`. Сейчас этим занимается функция `StartConsole`

**Итог**
Пока ставлю `90*0.6*0.4 = 21.6` и `10*0,6*0.5 = 3`

**Comment by mosssy1** [comment]
Добрый день, Андрей, поправила все недочеты во всех лабах, но, к сожалению, не могу понять недочеты 1,3 в программе HTMLDecode, можете рассказать пожалуйста, подробнее про них, если не затруднит

**Comment by Andreanapolicy** [comment]
3 пункт был про то, что в try-catch не будет происходить выбрасывание исключения, поэтому и не стоит оборачивать
1 пункт - слишком мало тестов. Советую добавить тесты, которые бы сломали написанную программу. Тесты, которые приходят в голову: строка, где html-сущность в начале и в конце строки, растянутая html-сущность(`&&&&&&&&amp;`). Стоит еще подумать, какие есть нестандартные кейсы
