### ISSUE TITLE
Замечания по 7 лабе

### ISSUE THREAD

**Issue by Andreanapolicy** [mosssy1/OOP#3]
# Задание 1
1. При написании шаблона не обязательно создавать файл `cpp`. Его можно и нужно удалить.
https://github.com/mosssy1/OOP/blob/01d70c8da3c4bec5b16e4d99fe393493fb886af0/lab7/FindMaxEx/FindMaxEx/CFindMaxEx.cpp#L1

2. Для чего тут нужно создавать указатель? Нельзя ли просто скопировать значение?
https://github.com/mosssy1/OOP/blob/01d70c8da3c4bec5b16e4d99fe393493fb886af0/lab7/FindMaxEx/FindMaxEx/CFindMaxEx.h#L11

3. Cоветую либо вынести функцию для ее переиспользования, либо использовать уже встроенную функцию в c++
https://github.com/mosssy1/OOP/blob/01d70c8da3c4bec5b16e4d99fe393493fb886af0/lab7/FindMaxEx/FindMaxEx_tests/FindMaxEx_tests.cpp#L13

4. Можно не указывать самостоятельно, что конструктор без параметров имеет дефолтную реализацию. Стоит убрать эту строчку
https://github.com/mosssy1/OOP/blob/01d70c8da3c4bec5b16e4d99fe393493fb886af0/lab7/FindMaxEx/FindMaxEx_tests/FindMaxEx_tests.cpp#L70

5. Стоит либо применить семантику `move` для строки, либо ее передать по константной ссылке.
https://github.com/mosssy1/OOP/blob/01d70c8da3c4bec5b16e4d99fe393493fb886af0/lab7/FindMaxEx/FindMaxEx_tests/FindMaxEx_tests.cpp#L72

6. стоит добавить тестов, которые показывают, что функция `FindMax` предоставляет строгую гарантию безопасности

# Задание 2
1. Для чего тут стоит вызов конструктора у типа? А если будет тип, у которого конструктор приватный?
https://github.com/mosssy1/OOP/blob/01d70c8da3c4bec5b16e4d99fe393493fb886af0/lab7/MyList/MyList/CMyListNode.hpp#L8
2. Для чего объявлять другом `CMyListConstIterator`?
https://github.com/mosssy1/OOP/blob/01d70c8da3c4bec5b16e4d99fe393493fb886af0/lab7/MyList/MyList/CMyListIterator.hpp#L18
3. Реализация классов `CMyListConstIterator` и `CMyListIterator` дублируются. Сделай так, чтобы они дублировались минимально(или вообще не дублировались)
https://github.com/mosssy1/OOP/blob/01d70c8da3c4bec5b16e4d99fe393493fb886af0/lab7/MyList/MyList/CMyListIterator.hpp#L79
4. Для чего тут был вызван `delete`? Выделялась ли для указателя новая память, чтобы ее ручками удалять?
https://github.com/mosssy1/OOP/blob/01d70c8da3c4bec5b16e4d99fe393493fb886af0/lab7/MyList/MyList/CMyList.hpp#L116
5. В задании нужно было также сделать конструктор перемещения и оператор присваивания через перемещение. Стоит их добавить.

*Тесты к `CMyList` написаны довольно хорошо. Много всего протестировано и базовые кейсы проверены. Мне понравилось.*

**Comment by mosssy1** [comment]
В 1 задании исправила пункты 1,2,5; пункт 4 компилятор не позволяет убрать, ругается на ошибку, не могу понять как именно нужно вынести в функцию в пункте 3 (тк функция итак вынесена в шаблоне), во 2 задании исправила 1,2,3,4 пункты

**Comment by Andreanapolicy** [comment]
# 1 задание
- 3 пункт - в c++ уже есть функция, которая позволяет сравнивать числа. Называется `less` https://en.cppreference.com/w/cpp/utility/functional/less
Тогда не придется постоянно дублировать лямбда-функцию
- 4 пункт - можно убрать конструктор без параметров, его допишет сам компилятор
- 6 пункт не выполнен.

Все остальное ок, поднял до 0.8

# 2 задание
- 3 пункт: сейчас у тебя константный итератор и неконстантный похожи, хотя должны отдавать разные значения(const и не const значения).

Все остальное ок, поднял до 0.9
